In [ ]:
import numpy as np


In [ ]:
arrange_array=np.arange(0,10,2)  # start=0, stop=10, step=2
print(arrange_array)

[0 2 4 6 8]


In [ ]:
identity_matrix=np.eye(3)  # 3x3 identity matrix
print(identity_matrix)


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
shpe_array=np.array([[1,2,4]])
print(shpe_array.shape)

(1, 3)


In [ ]:
size_array=np.array([[1,2,4]])
print(size_array.size)  # returns the size of the array that is 3

3


In [ ]:
ndim_array1=np.array([1,2,3])
ndim_array2=np.array([[1,2,4]])
ndim_array3=np.array([[[1,2,3],[4,5,6]]])
print(ndim_array1.ndim)  # returns the number of dimensions of the array that is 1D array so it returns 1
print(ndim_array2.ndim)  # returns the number of dimensions of the array that is 2D array so it returns 2
print(ndim_array3.ndim)

1
2
3


In [ ]:
dtype_array=np.array([1,2,3.4,5,3])
print(dtype_array.dtype)

float64


In [ ]:
astype_array=np.array([1,2,3,4,5])
new_type=astype_array.astype(float)
print(astype_array.astype(float))
print(new_type.dtype)

[1. 2. 3. 4. 5.]
float64


In [ ]:
add_array1 = np.array([1, 2, 3])
add_array2 = np.array([4, 5, 6])
print("addition:",add_array1 + add_array2)

add_ones =np.ones((1,3),dtype='int')
print("addition with ones:",add_array1 + add_ones)
print((add_array1+add_ones).dtype)
print((add_array1+add_array2).dtype)

addition: [5 7 9]
addition with ones: [[2 3 4]]
int64
int64


In [ ]:
sum_array=np.array([12,3,5])
print("sum: ",np.sum(sum_array))
print("min: ",np.min(sum_array))
print("mean: ",np.mean(sum_array))
print("max: ",np.max(sum_array))
print("standard deviation: ",np.std(sum_array))
print("variance: ",np.var(sum_array))

sum:  20
min:  3
mean:  6.666666666666667
max:  12
standard deviation:  3.858612300930075
variance:  14.888888888888888


In [ ]:
print_array=np.array([1,2,3,4,5,6])
print(print_array)

[1 2 3 4 5 6]


In [ ]:
print_zeros=np.zeros(3)
print(print_zeros)

[0. 0. 0.]


In [ ]:
print_ones=np.ones(3)
print(print_ones)

[1. 1. 1.]


In [ ]:
array_sort=np.array([1,42,39,0])
print(np.sort(array_sort))

[ 0  1 39 42]


In [ ]:
print_List=[1,2,3,4,5]
print(print_List)

[1, 2, 3, 4, 5]


In [ ]:
#indexing and slicing
arr=np.array([10,20,30,40,50])
print(arr[0])
print(arr[-1])  #prints the last element
print(arr[1:5])
print(arr[::2])
print(arr[::-1])  #this will reverse the array

10
50
[20 30 40 50]
[10 30 50]
[50 40 30 20 10]


In [ ]:
#fancy indexing : selecting multiple elements at once
array=np.array([10,20,30,40,50,60])
print(array[[0,2,4]])

[10 30 50]


In [ ]:
array=np.array([1, 2, 3, 4, 5, 6])
print(array[array > 3])  # prints elements greater than 3

[4 5 6]


In [ ]:
array = np.array([1, 2, 3, 4, 5, 6])
reshaped_array = array.reshape((2, 3))  # reshaping to 2 rows and 3 columns
print("reshaped array:\n", reshaped_array)

reshaped array:
 [[1 2 3]
 [4 5 6]]


In [ ]:
array_2d = np.array([[1, 2, 3], [4, 5, 6]])
print(array_2d.flatten())
print(array_2d.ravel())

[1 2 3 4 5 6]
[1 2 3 4 5 6]


In [ ]:
insert_array = np.array([1, 2, 3])
inserted_array = np.insert(insert_array, 1, 4 , axis=None)  # inserting along the rows
print("inserted array:\n", inserted_array)

appended_array = np.append(insert_array, 4,axis=None)  # appending to the end of the array
print("appended array:\n", appended_array)


concatenated_array = np.concatenate((inserted_array, appended_array), axis=None)  # concatenating two arrays
print("concatenated array:\n", concatenated_array)


deleted_array = np.delete(inserted_array, 3, axis=None)  # deleting the element at index 1
print("deleted array:\n", deleted_array)

inserted array:
 [1 4 2 3]
appended array:
 [1 2 3 4]
concatenated array:
 [1 4 2 3 1 2 3 4]
deleted array:
 [1 4 2]


In [ ]:
insert_array2d = np.array([[1, 2], [3, 4]])
inserted_array2d = np.insert(insert_array2d, 1, [5, 6], axis=0)  # inserting along the rows
print("inserted 2D array along rows:\n", inserted_array2d)

inserted_array2d = np.insert(insert_array2d, 1, [7, 8], axis=1)  # inserting along the rows
print("inserted 2D array along column:\n", inserted_array2d)

inserted 2D array along rows:
 [[1 2]
 [5 6]
 [3 4]]
inserted 2D array along column:
 [[1 7 2]
 [3 8 4]]


In [ ]:
arr1=np.array([1, 2, 3, 4])
arr2=np.array([5, 6, 7, 8])
print("vertical stacking:\n", np.vstack((arr1, arr2)))  # vertical stacking
print("horizontal stacking:\n", np.hstack((arr1, arr2)))  # horizontal stacking

vertical stacking:
 [[1 2 3 4]
 [5 6 7 8]]
horizontal stacking:
 [1 2 3 4 5 6 7 8]


In [ ]:
split_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("split array:", np.split(split_array, 3))  # splitting into 3 sub-arrays along the rows
print("horizontal split:", np.hsplit(split_array, 3))  # horizontal splitting into 3 sub-arrays
print("vertical split:", np.vsplit(split_array, 3))  # vertical splitting into 3 sub-array

split array: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]
horizontal split: [array([[1],
       [4],
       [7]]), array([[2],
       [5],
       [8]]), array([[3],
       [6],
       [9]])]
vertical split: [array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]


In [ ]:
prices = np.array([100, 200, 300])
discount=10
final_prices=prices-(prices * discount / 100)  # applying a discount of 10% to each price
print("final prices after discount:\n", final_prices)

final prices after discount:
 [ 90. 180. 270.]


In [ ]:
array1 = np.array([1, 2, 3, 4, 5])
array2 = np.array([6, 7, 8, 9, 10])
#using vectorized operations instead of loops
result = array1 + array2  # adding two arrays element-wise
print("vectorized result:\n", result)

vectorized result:
 [ 7  9 11 13 15]


In [ ]:
array_with_nan = np.array([1, 2, np.nan, 4, 5])
#checking for missing values
print("missing values in array:", np.isnan(array_with_nan))  # returns a boolean array indicating missing values
filled_array_with_nan = np.nan_to_num(array_with_nan, nan=0)  # filling missing values with 0
print("filled array with nan:\n", filled_array_with_nan)  # filling missing values with 0

missing values in array: [False False  True False False]
filled array with nan:
 [1. 2. 0. 4. 5.]


In [ ]:
array_with_inf = np.array([1, 2 , np.inf , -np.inf, 4, 5])
#checking for infinite values
print("infinite values in array:", np.isinf(array_with_inf))  # returns a boolean array indicating infinite values
#filling infinite values
filled_array_with_inf = np.nan_to_num(array_with_inf, posinf=10, neginf=20)  # filling infinite values with 0
print("filled array with inf:\n", filled_array_with_inf)  # filling infinite values with 0


infinite values in array: [False False  True  True False False]
filled array with inf:
 [ 1.  2. 10. 20.  4.  5.]
